root: true
env:
  node: true
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:vue/vue3-recommended
  - prettier
parserOptions:
  ecmaVersion: 2021
  sourceType: module
plugins:
  - vue
  - html
  - prettier
rules:
  prettier/prettier: 2
  vue/multi-word-component-names: 0